import random
from Enemy import *

class Ogre(Enemy):
    def __init__(self,health,attack):
        super().__init__(enemytype="Ogre",
                         health=health,
                         attack=attack)


    def special_attack(self):
        did_special_attack_work = random.random()<0.20
        if did_special_attack_work:
            self.attack+=4
            print(f" Zombie regenerated by attack: {self.attack}")