from Enemy import *
import random

class Zombie(Enemy):
    def __init__(self,health,attack):
        super().__init__(enemytype='Zombie',
                         health=health,
                         attack=attack)

    def talk(self):
        print((f"this is the zomboe that is going to eat you got it!@"))

    def spraad(self):
        print("Zombie spread the disease")

    def special_attack(self):
        did_special_attack_work = random.random()<0.50
        if did_special_attack_work:
            self.health+=2
            print(f" Zombie regenerated by Health: {self.health}")